In [1]:
import pandas as pd
import numpy as np 

import matplotlib.pyplot as plt
import seaborn as sns

In [65]:
pd.set_option("Display.max_rows", 1000)
pd.set_option("Display.max_columns", 25)

In [66]:
vehicles_data = pd.read_csv("Data/2012-2023 Battery Electric Vehicles.csv")
fuel_consumption_data = pd.read_csv("Data/MY2023 Fuel Consumption Ratings.csv", encoding='cp1252')

In [68]:
vehicles_data.head()

,Model_Year,Make,Model,Vehicle_Class,Motor_kW,Transmission,Fuel_Type,Consumption_City_kWh/100 km,Consumption_Hwy_kWh/100 km,Consumption_Comb_kWh/100 km,Consumption_City_Le/100 km,Consumption_Hwy_Le/100 km,Consumption_Comb_Le/100 km,Range_km,CO2 Emissions_g/km,CO2_rating,Smog_rating,Recharge_time_h
0,2012,Mitsubishi,i-MiEV,Subcompact,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,100,0,NaN,NaN,7.0
1,2012,Nissan,LEAF,Mid-size,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,117,0,NaN,NaN,7.0
2,2013,Ford,Focus Electric,Compact,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,122,0,NaN,NaN,4.0
3,2013,Mitsubishi,i-MiEV,Subcompact,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,100,0,NaN,NaN,7.0
4,2013,Nissan,LEAF,Mid-size,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,117,0,NaN,NaN,7.0

In [69]:
fuel_consumption_data.head()

,Model_Year,Make,Model,Vehicle Class,Engine Size(L),Cylinders,Transmission,Fuel_Type,Fuel Consumption City (L/100 km),Hwy (L/100 km),Comb (L/100 km),Comb (mpg),CO2 Emissions(g/km),CO2 Rating,Smog Rating
0,2023,Acura,Integra,Full-size,1.5,4.0,AV7,Z,7.9,6.3,7.2,39.0,167.0,6.0,7.0
1,2023,Acura,Integra A-SPEC,Full-size,1.5,4.0,AV7,Z,8.1,6.5,7.4,38.0,172.0,6.0,7.0
2,2023,Acura,Integra A-SPEC,Full-size,1.5,4.0,M6,Z,8.9,6.5,7.8,36.0,181.0,6.0,6.0
3,2023,Acura,MDX SH-AWD,SUV: Small,3.5,6.0,AS10,Z,12.6,9.4,11.2,25.0,263.0,4.0,5.0
4,2023,Acura,MDX SH-AWD Type S,SUV: Standard,3.0,6.0,AS10,Z,13.8,11.2,12.4,23.0,291.0,4.0,5.0

### Basic Data Preprocessing and EDA

In [70]:
vehicles_data.columns

Index(['Model_Year', 'Make', 'Model', 'Vehicle_Class', 'Motor_kW',
       'Transmission', 'Fuel_Type', 'Consumption_City_kWh/100 km',
       'Consumption_Hwy_kWh/100 km', 'Consumption_Comb_kWh/100 km',
       'Consumption_City_Le/100 km', 'Consumption_Hwy_Le/100 km',
       'Consumption_Comb_Le/100 km', 'Range_km', 'CO2 Emissions_g/km',
       'CO2_rating', 'Smog_rating', 'Recharge_time_h'],
      dtype='object')

In [26]:
vehicles_data.head(1)

,Model_Year,Make,Model,Vehicle_Class,Motor_kW,Transmission,Fuel_Type,Consumption_City_kWh/100 km,Consumption_Hwy_kWh/100 km,Consumption_Comb_kWh/100 km,Consumption_City_Le/100 km,Consumption_Hwy_Le/100 km,Consumption_Comb_kWh/100 km.1,Range_km,CO2 Emissions_g/km,CO2_rating,Smog_rating,Recharge_time_h
0,2012,Mitsubishi,i-MiEV,Subcompact,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,100,0,NaN,NaN,7.0

In [25]:
vehicles_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 411 entries, 0 to 410
Data columns (total 18 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Model_Year                     411 non-null    int64
 1   Make                           411 non-null    object
 2   Model                          411 non-null    object
 3   Vehicle_Class                  411 non-null    object
 4   Motor_kW                       411 non-null    int64
 5   Transmission                   411 non-null    object
 6   Fuel_Type                      411 non-null    object
 7   Consumption_City_kWh/100 km    411 non-null    float64
 8   Consumption_Hwy_kWh/100 km     411 non-null    float64
 9   Consumption_Comb_kWh/100 km    411 non-null    float64
 10  Consumption_City_Le/100 km     411 non-null    float64
 11  Consumption_Hwy_Le/100 km      411 non-null    float64
 12  Consumption_Comb_kWh/100 km.1  411 non-null    float64
 13  Range_km                       411 non-null    int64
 14  CO2 Emissions_g/km             411 non-null    int64
 15  CO2_rating                     377 non-null    float64
 16  Smog_rating                    350 non-null    float64
 17  Recharge_time_h                411 non-null    float64
dtypes: float64(9), int64(4), object(5)
memory usage: 57.9+ KB

Vehicles Company and Making Year

In [31]:
vehicles_data['Model_Year'].value_counts(normalize = True) * 100

2023    24.330900
2022    19.951338
2021    11.922141
2020     9.732360
2019     8.515815
2016     6.569343
2017     5.596107
2018     5.109489
2015     3.406326
2013     2.189781
2014     2.189781
2012     0.486618
Name: Model_Year, dtype: float64

In [33]:
vehicles_data.Make.value_counts()[:10]

Tesla        132
BMW           36
Ford          31
Kia           26
Porsche       21
Nissan        20
Audi          18
Hyundai       16
Lucid         15
Chevrolet     12
Name: Make, dtype: int64

In [43]:
vehicles_data.groupby(['Make', 'Model'])['Model'].count()

Make           Model
Audi           Q4 50 e-tron Sportback quattro                     1
               Q4 50 e-tron quattro                               2
               Q4 Sportback 50 e-tron quattro                     1
               RS e-tron GT                                       2
               e-tron 55 quattro                                  4
               e-tron GT                                          2
               e-tron S Sportback quattro (20" Wheels)            1
               e-tron S Sportback quattro (21" or 22" Wheels)     1
               e-tron Sportback 55 quattro                        4
BMW            i3                                                 3
               i3 (120 Ah)                                        3
               i3 (60 Ah)                                         1
               i3 (94 Ah)                                         1
               i3s                                                1
               i3s (120 Ah)                                       3
               i4 M50 Gran Coupe (19" Wheels)                     1
               i4 M50 Gran Coupe (20" Wheels)                     1
               i4 M50 xDrive (19" Wheels)                         1
               i4 M50 xDrive (20" Wheels)                         1
               i4 eDrive35 Gran Coupe (18" Wheels)                1
               i4 eDrive35 Gran Coupe (19" Wheels)                1
               i4 eDrive40 (18" Wheels)                           1
               i4 eDrive40 (19" Wheels)                           1
               i4 eDrive40 Gran Coupe (18" Wheels)                1
               i4 eDrive40 Gran Coupe (19" Wheels)                1
               i7 xDrive60 (19" Wheels)                           1
               i7 xDrive60 (20" Wheels)                           1
               i7 xDrive60 (21" Wheels)                           1
               iX M60 (21" Wheels)                                1
               iX M60 (22" Wheels)                                1
               iX xDrive40 (20" Wheels)                           1
               iX xDrive40 (21" Wheels)                           1
               iX xDrive40 (22" Wheels)                           1
               iX xDrive50 (20" Wheels)                           2
               iX xDrive50 (21" Wheels)                           2
               iX xDrive50 (22" Wheels)                           2
Cadillac       LYRIQ                                              1
               LYRIQ AWD                                          1
Chevrolet      Bolt EUV                                           2
               Bolt EV                                            7
               Spark EV                                           3
Ford           F-150 Lightning Extended Range                     2
               F-150 Lightning Platinum                           2
               F-150 Lightning Standard Range                     2
               Focus Electric                                     6
               Mustang Mach-E California Route 1                  2
               Mustang Mach-E California Route 1 AWD              2
               Mustang Mach-E Extended Range                      2
               Mustang Mach-E Extended Range (19" Wheels)         1
               Mustang Mach-E Extended Range AWD                  3
               Mustang Mach-E GT Performance Edition              3
               Mustang Mach-E Standard Range                      3
               Mustang Mach-E Standard Range AWD                  3
Genesis        Electrified G80                                    1
               Electrified GV70                                   1
               GV60 Advanced AWD                                  1
               GV60 Performance AWD                               1
Hyundai        IONIQ 5 Long Range                                 2
               IONIQ 5 Long Range AWD                             2
               IONIQ 5 Standard Range                             2
               IONIQ Electric                                     5
               Kona Electric                                      5
Jaguar         I-PACE                                             4
Kia            EV6 GT AWD                                         1
               EV6 Long Range                                     2
               EV6 Long Range AWD                                 1
               EV6 Long Range AWD (19" Wheels)                    1
               EV6 Long Range AWD (20" Wheels)                    1
               EV6 Standard Range                                 2
               Niro EV                                            5
               Soul EV                                            5
               Soul EV (120 Ah)                                   4
               Soul EV (180 Ah)                                   4
Lucid          Air Dream P AWD (19" Wheels)                       1
               Air Dream P AWD (21" Wheels)                       1
               Air Dream R AWD (19" Wheels)                       1
               Air Dream R AWD (21" Wheels)                       1
               Air Grand Touring AWD (19" Wheels)                 1
               Air Grand Touring AWD (21" Wheels)                 1
               Air Grand Touring Performance (21" Wheels)         1
               Air Grand Touring XR (19" Wheels)                  1
               Air Grand Touring XR (20" Wheels)                  1
               Air Grand Touring XR (21" Wheels)                  1
               Air Pure (19" Wheels)                              1
               Air Pure (20" Wheels)                              1
               Air Touring (19" Wheels)                           1
               Air Touring (20" Wheels)                           1
               Air Touring (21" Wheels)                           1
MINI           Cooper SE 3 Door                                   4
Mazda          MX-30                                              2
Mercedes-Benz  AMG EQE 4MATIC+ Sedan                              1
               AMG EQS 4MATIC+ Sedan                              1
               EQB 350 4MATIC SUV                                 2
               EQS 450 4MATIC SUV                                 1
               EQS 580 4MATIC SUV                                 1
               EQS 580 4MATIC Sedan                               2
Mitsubishi     i-MiEV                                             6
Nissan         LEAF                                               6
               LEAF (24 kWh)                                      1
               LEAF (30 kWh)                                      1
               LEAF (40 kWh)                                      4
               LEAF S PLUS                                        4
               LEAF SV/SL PLUS                                    4
Polestar       2                                                  1
               2 BST Edition                                      1
               2 Dual Motor                                       2
               2 Dual Motor Performance Pack                      1
               2 Single Motor                                     2
Porsche        Taycan 4 Cross Turismo                             2
               Taycan 4S (Performance Battery Plus)               3
               Taycan 4S (Performance Battery)                    2
               Taycan 4S Cross Turismo                            2
               Taycan GTS                                         1
               Taycan GTS Sport Turismo                           1
               Taycan Turbo                                       3
               Taycan Turbo Cross Turismo                         2
               Taycan Turbo S                                     3
               Taycan Turbo S Cross Turismo                       2
Rivian         R1S                                                1
               R1S (20" Wheels)                                   1
               R1S (21" Wheels)                                   1
               R1S (22" Wheels)                                   1
               R1T                                                1
               R1T (20" Wheels)                                   1
               R1T (21" Wheels)                                   1
               R1T (22" Wheels)                                   1
Subaru         Solterra AWD                                       1
Tesla          Model 3 Long Range                                 3
               Model 3 Long Range AWD                             6
               Model 3 Long Range AWD Performance                 2
               Model 3 Long Range AWD Performance (18" Wheels)    1
               Model 3 Long Range AWD Performance (19" Wheels)    1
               Model 3 Long Range AWD Performance (20" Wheels)    1
               Model 3 Mid Range                                  3
               Model 3 Performance                                3
               Model 3 RWD                                        2
               Model 3 Standard Range                             4
               Model 3 Standard Range Plus                        3
               Model S                                            2
               Model S (40 kWh)                                   1
               Model S (60 kWh pre- 6/16)                         1
               Model S (60 kWh)                                   5
               Model S (70 kWh)                                   2
               Model S (75 kWh)                                   3
               Model S (85 kWh)                                   2
               Model S (85/90 kWh)                                2
               Model S 100D                                       3
               Model S 60D                                        2
               Model S 70D                                        2
               Model S 75D                                        4
               Model S 85D/90D                                    2
               Model S 90D                                        1
               Model S 90D (Refresh)                              1
               Model S Long Range                                 3
               Model S Long Range Plus                            2
               Model S Long Range Plus (pre-15/6/20)              1
               Model S P100D                                      3
               Model S P85D/P90D                                  2
               Model S P90D                                       1
               Model S P90D (Refresh)                             1
               Model S Performance                                2
               Model S Performance (19" Wheels)                   3
               Model S Performance (21" Wheels)                   3
               Model S Plaid (19" Wheels)                         3
               Model S Plaid (21" Wheels)                         3
               Model S Standard Range                             2
               Model X                                            2
               Model X 100D                                       2
               Model X 75D                                        3
               Model X 90D                                        1
               Model X Long Range                                 3
               Model X Long Range Plus                            2
               Model X P100D                                      3
               Model X P90D                                       1
               Model X Performance (20" Wheels)                   3
               Model X Performance (22" Wheels)                   3
               Model X Plaid (20" Wheels)                         2
               Model X Plaid (22" Wheels)                         2
               Model X Standard Range                             2
               Model Y AWD                                        2
               Model Y Long Range AWD                             4
               Model Y Performance                                4
               Model Y Performance (21" Wheels)                   1
               Model Y Standard Range                             1
Tesla          Model S P100D                                      1
               Model X 100D                                       1
               Model X 60D                                        2
               Model X 75D                                        1
               Model X 90D                                        1
               Model X P100D                                      1
               Model X P90D                                       1
Toyota         bZ4X                                               1
               bZ4X AWD                                           1
Volkswagen     ID.4                                               1
               ID.4 AWD Pro                                       3
               ID.4 Pro                                           3
               e-Golf                                             4
Volvo          C40 Recharge Twin                                  2
               XC40 Recharge                                      1
               XC40 Recharge Twin                                 2
smart          fortwo electric drive cabriolet                    5
               fortwo electric drive coupe                        5
smart EQ       fortwo cabriolet                                   1
               fortwo coupe                                       1
Name: Model, dtype: int64

In [44]:
vehicles_data.columns

Index(['Model_Year', 'Make', 'Model', 'Vehicle_Class', 'Motor_kW',
       'Transmission', 'Fuel_Type', 'Consumption_City_kWh/100 km',
       'Consumption_Hwy_kWh/100 km', 'Consumption_Comb_kWh/100 km',
       'Consumption_City_Le/100 km', 'Consumption_Hwy_Le/100 km',
       'Consumption_Comb_kWh/100 km.1', 'Range_km', 'CO2 Emissions_g/km',
       'CO2_rating', 'Smog_rating', 'Recharge_time_h'],
      dtype='object')

In [46]:
vehicles_data['Fuel_Type'].value_counts()   #unique fuel types, only electricity

B    411
Name: Fuel_Type, dtype: int64

In [47]:
vehicles_data['Vehicle_Class'].value_counts()

Full-size                 93
Mid-size                  77
SUV: Standard             63
SUV: Small                58
Station wagon: Small      41
Subcompact                35
Compact                   22
Two-seater                12
Pickup truck: Standard    10
Name: Vehicle_Class, dtype: int64

Which company is providing most full-size cars?

In [62]:
vehicles_data.query("`Vehicle_Class` == 'Full-size'")['Make'].value_counts().reset_index().rename(
    columns = {'index': "Company", 'Make':'No of Cars'}
)[:1]

  Company  No of Cars
0   Tesla          62